export const COPY = {
  APP_TITLE: 'DEV REBIRTH',
  APP_SUBTITLE: 'Act like a developer. Become one.',
  
  INITIALIZE_BUTTON: 'INITIALIZE DAY 1',
  
  SECTIONS: {
    MORNING: 'MORNING',
    AFTERNOON: 'AFTERNOON',
    EVENING: 'EVENING',
    NIGHT: 'NIGHT'
  },
  
  REALITY_CHECK: 'REALITY CHECK',
  DISCIPLINE_SCORE: 'DISCIPLINE SCORE',
  
  SUMMARY_HIGH: 'REAL DEVELOPER ACTIONS RECORDED.',
  SUMMARY_MEDIUM: 'PROGRESS MADE. STAY CONSISTENT.',
  SUMMARY_LOW: 'LESS TALK. MORE BUILDING TOMORROW.',
  
  REALITY_DOMINATES: 'DISCIPLINE DOMINATES.',
  REALITY_DISTRACTIONS: 'REALITY CHECK: DISTRACTIONS DOMINATE.',
  
  DISCIPLINE_HIGHLY: 'HIGHLY DISCIPLINED',
  DISCIPLINE_IMPROVING: 'IMPROVING',
  DISCIPLINE_LOSING: 'LOSING CONTROL',
  
  WARNING_SLIPPING: 'WARNING: YOU ARE SLIPPING.',
  
  RELEVANCE_LABEL: 'How relevant were your actions toward becoming a real developer?'
};
