const DISCIPLINE_QUOTES = [
  "CODE EVERY DAY. NO EXCUSES.",
  "DISCIPLINE BEATS MOTIVATION.",
  "BUILD. SHIP. REPEAT.",
  "REAL DEVELOPERS SHOW UP DAILY.",
  "YOUR FUTURE IS BUILT TODAY.",
  "CONSISTENCY IS THE WEAPON.",
  "STOP PLANNING. START BUILDING.",
  "EVERY LINE OF CODE COUNTS.",
  "DISCIPLINE IS FREEDOM.",
  "THE GRIND NEVER STOPS.",
  "ACTIONS SPEAK. CODE LOUDER.",
  "ZERO DAYS ARE UNACCEPTABLE.",
  "PROGRESS OVER PERFECTION.",
  "SHIP BEFORE YOU'RE READY.",
  "DEVELOPERS ARE MADE, NOT BORN."
];

export function getDailyQuote(dateKey: string): string {
  const hash = dateKey.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  return DISCIPLINE_QUOTES[hash % DISCIPLINE_QUOTES.length];
}
